# 参考サイト
# https://tekkubu.com/docker-jupyter-lab/
# https://zenn.dev/nigimitama/articles/2022-11-23-docker-example-for-jupyterlab
# 将来的にはこうしたい
# https://qiita.com/sho-hata/items/02ad47f67bce6816a69a
version: '3'
services:
   jupyterlab:
    container_name: "JupyterLab"
    build:
      # コンテナ構築に使うDockerfileを指定（docker-compose.ymlのあるディレクトリからの相対パス）
      dockerfile: "./docker/python/Dockerfile"
    ports:
      - 8888:8888
#      - "8000:8000"
    # ローカルPCのディレクトリをDockerコンテナにマウント
    # こうすることで、ローカルPCのファイルを変更すると、コンテナ内部もリアルタイムで変更される
    volumes:
      - ./data:/app/data
      - ./scrape用:/app/scrape用
      - ./データ整形用:/app/データ整形用
      - ./モデル作成:/app/モデル作成
      - ./分析用:/app/分析用
    # 初回起動時にjupyterlabの起動設定をする。
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/app
    tty: true