version: '3'
services:
   jupyterlab:
    container_name: "JupyterLab"
    build:
      # コンテナ構築に使うDockerfileを指定（docker-compose.ymlのあるディレクトリからの相対パス）
      dockerfile: "./docker/python/Dockerfile"
    ports:
      - 8888:8888

    # ローカルPCのディレクトリをDockerコンテナにマウント
    # こうすることで、ローカルPCのファイルを変更すると、コンテナ内部もリアルタイムで変更される
    volumes:
      - ./:/app/
      # - ./data:/app/data
      # - ./scrape用:/app/scrape用
      # - ./データ整形用:/app/データ整形用
      # - ./モデル作成:/app/モデル作成
      # - ./分析用:/app/分析用
    # 初回起動時にjupyterlabの起動設定をする。
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/app
    tty: true
